### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by ralftar** [vendanor/preview-pull-request#224]
Lots of these.

**Comment by ralftar** [comment]
@thomastvedt do you know where these come from? Was unable to find them in the source code at first glance.

**Comment by jonaski** [comment]
set-output is not in our code. We have updated all packages.

**Comment by thomastvedt** [comment]
I think we can close this @ralftar , we could not reproduce the warning message after bumping packages. v3.11.
