### ISSUE TITLE
Rename to VnPreviewAction

### ISSUE THREAD

**Issue by ralftar** [vendanor/preview-pull-request#7]
Blocked by https://github.com/vendanor/VnPreviewAction/issues/1

**Comment by thomastvedt** [comment]
Name suggestions:
1. VnPreviewAction
2. VnPullRequestPreviewAction
3. vn-pull-request-preview
4. preview-pull-request

Github actions uses hyphens as a naming convention, example: `company/my-awesome-action@v1`  
`uses: vendanor/VnPreviewAction@v1.5`
or
`uses: vendanor/preview-pull-request@v1.5`

If we want to follow Github action naming conventions and communicate the purpose of the action we should choose number 4? And if we want to follow our own repository naming convention, number 1 :) 

@ralftar

**Comment by ralftar** [comment]
I have been thinking for a while that we must use an other names for the public repos, so I agree on option 4 🎯
